// auto-generated by cdc compiler

.section .text
.global foo
foo:
pushq %rbp
movq %rsp, %rbp
subq $0, %rsp
// save register params
// save stack params
movl $1, %eax
movq %rbp, %rsp
popq %rbp
ret
movl $0, %eax
movq %rbp, %rsp
popq %rbp
ret
.global bar
bar:
pushq %rbp
movq %rsp, %rbp
subq $0, %rsp
// save register params
// save stack params
movl $2, %eax
movq %rbp, %rsp
popq %rbp
ret
movl $0, %eax
movq %rbp, %rsp
popq %rbp
ret
.section .note.GNU-stack,"",@progbits
