
import 'package:cdc/asm_generators/x86_64/x86_64_asm.dart';

class X8664AsmEmitter implements X8664FunctionAsmVisitor<String>, X8664InstrVisitor<String>, X8664OperandVisitor<String> {
  static String emit(X8664ProgramASM program) => X8664AsmEmitter().visitProgram(program);
  
  String visitProgram(X8664ProgramASM x8664programASM) =>
    """
// auto-generated by cdc compiler

.section .text
${x8664programASM.mainFunction.accept(this)}
.section .note.GNU-stack,"",@progbits
""";
  
  @override
  String visitX8664FunctionAsm(X8664FunctionAsm function) => 
// TODO: unhardcode stack manipulation
"""
.global ${function.name}
${function.name}:
pushq %rbp
movq %rsp, %rbp
${function.instrs.map((inst) => inst.accept(this)).join('\n')}""";

  @override
  String visitAllocateStackX8664Instr(AllocateStackX8664Instr alloc) => "subq \$${alloc.amount}, %rsp";
  
  @override
  String visitBinaryX8664Instr(BinaryX8664Instr binaryX8664Instr) => 
    "${binaryX8664Instr.operator.name}l ${binaryX8664Instr.lhs.accept(this)}, ${binaryX8664Instr.rhs.accept(this)}";
  
  @override
  String visitImmediateX8664Operand(ImmediateX8664Operand immediateX8664Operand) => "\$${immediateX8664Operand.value}";
  
  @override
  String visitMoveX8664Instr(MoveX8664Instr moveX8664Instr) => 
    "movl ${moveX8664Instr.src.accept(this)}, ${moveX8664Instr.dst.accept(this)}";
  
  @override
  String visitPseudoX8664Operand(PseudoX8664Operand pseudoX8664Operand) => 
    throw Exception("final asm program ast must not contain pseudo operand.");
  
  @override
  String visitReturnX8664Instr(ReturnX8664Instr returnX8664Instr) => 
    """
movq %rbp, %rsp
popq %rbp
ret""";
  
  @override
  String visitStackX8664Operand(StackX8664Operand stackX8664Operand) => "-${stackX8664Operand.value}(%rbp)";
  
  @override
  String visitUnaryX8664Instr(UnaryX8664Instr unaryX8664Instr) => 
    "${unaryX8664Instr.operator.name}l ${unaryX8664Instr.operand.accept(this)}";
  
  @override
  String visitRegisterX8664Operand(RegisterX8664Operand registerX8664Operand) => 
    "%${registerX8664Operand.reg.names[registerX8664Operand.size]}";
    
  @override
  String visitCdqX8664Instr(CdqX8664Instr cdqX8664Instr) => "cdq";

  @override
  String visitIdivX8664Instr(IdivX8664Instr idivX8664Instr) => 
    "idivl ${idivX8664Instr.operand.accept(this)}";
    
  @override
  String visitCmpX8664Instr(CmpX8664Instr cmpX8664Instr) => 
    "cmpl ${cmpX8664Instr.lhs.accept(this)}, ${cmpX8664Instr.rhs.accept(this)}";

  @override
  String visitJmpCCX8664Instr(JmpCCX8664Instr jmpCcx8664Instr) =>
    "j${jmpCcx8664Instr.condCode.name} .L${jmpCcx8664Instr.identifier}";

  @override
  String visitJmpX8664Instr(JmpX8664Instr jmpX8664Instr) =>
    "jmp .L${jmpX8664Instr.identifier}";

  @override
  String visitLabelX8664Instr(LabelX8664Instr labelX8664Instr) =>
    ".L${labelX8664Instr.identifier}:";

  @override
  String visitSetCCX8664Instr(SetCCX8664Instr setCcx8664Instr) {
    final operand = setCcx8664Instr.operand is RegisterX8664Operand 
      ? RegisterX8664Operand((setCcx8664Instr.operand as RegisterX8664Operand).reg, .lowByte).accept(this)
      : setCcx8664Instr.operand.accept(this);

    return "set${setCcx8664Instr.condCode.name} $operand";
  }
}