import 'package:cdc/cdc.dart';

part 'x86_64_asm.g.dart';

class X8664ProgramASM implements ProgramASM {
  final X8664FunctionASM function;

  X8664ProgramASM(this.function);

  @override
  String emit() => X8664AsmEmitter.emit(this);

  @override
  String toString() => X8664AsmPrettifier.prettify(this);
}

// TODO: move to a separate file
class X8664AsmEmitter implements X8664InstrVisitor<String>, X8664OperandVisitor<String> {
  static String emit(X8664ProgramASM program) => X8664AsmEmitter().visitProgram(program);
  
  String visitProgram(X8664ProgramASM x8664programASM) =>
    """
// auto-generated by cdc compiler

.section .text
${visitFunction(x8664programASM.function)}
.section .note.GNU-stack,"",@progbits
""";
  
  String visitFunction(X8664FunctionASM function) => 
"""
.global ${function.name}
${function.name}:
pushq %rbp
movq %rsp, %rbp
${function.instrs.map((inst) => inst.accept(this)).join('\n')}""";

  @override
  String visitAllocateStackX8664Instr(AllocateStackX8664Instr alloc) => "subq \$${alloc.amount}, %rsp";
  
  @override
  String visitBinaryX8664Instr(BinaryX8664Instr binaryX8664Instr) => 
    "${binaryX8664Instr.operator.name}l ${binaryX8664Instr.lhs.accept(this)}, ${binaryX8664Instr.rhs.accept(this)}";
  
  @override
  String visitImmediateX8664Operand(ImmediateX8664Operand immediateX8664Operand) => "\$${immediateX8664Operand.value}";
  
  @override
  String visitMoveX8664Instr(MoveX8664Instr moveX8664Instr) => 
    "movl ${moveX8664Instr.src.accept(this)}, ${moveX8664Instr.dst.accept(this)}";
  
  @override
  String visitPseudoX8664Operand(PseudoX8664Operand pseudoX8664Operand) => 
    throw Exception("final asm program ast must not contain pseudo operand.");
  
  @override
  String visitReturnX8664Instr(ReturnX8664Instr returnX8664Instr) => 
    """
movq %rbp, %rsp
popq %rbp
ret""";
  
  @override
  String visitStackX8664Operand(StackX8664Operand stackX8664Operand) => "-${stackX8664Operand.value}(%rbp)";
  
  @override
  String visitUnaryX8664Instr(UnaryX8664Instr unaryX8664Instr) => 
    "${unaryX8664Instr.operator.name}l ${unaryX8664Instr.operand.accept(this)}";
  
  @override
  String visitRegisterX8664Operand(RegisterX8664Operand registerX8664Operand) => 
    "%${registerX8664Operand.reg.names[registerX8664Operand.size]}";
    
  @override
  String visitCdqX8664Instr(CdqX8664Instr cdqX8664Instr) => "cdq";

  @override
  String visitIdivX8664Instr(IdivX8664Instr idivX8664Instr) => 
    "idivl ${idivX8664Instr.operand.accept(this)}";
    
  @override
  String visitCmpX8664Instr(CmpX8664Instr cmpX8664Instr) => 
    "cmpl ${cmpX8664Instr.lhs.accept(this)}, ${cmpX8664Instr.rhs.accept(this)}";

  @override
  String visitJmpCCX8664Instr(JmpCCX8664Instr jmpCcx8664Instr) =>
    "j${jmpCcx8664Instr.condCode.name} .L${jmpCcx8664Instr.identifier}";

  @override
  String visitJmpX8664Instr(JmpX8664Instr jmpX8664Instr) =>
    "jmp .L${jmpX8664Instr.identifier}";

  @override
  String visitLabelX8664Instr(LabelX8664Instr labelX8664Instr) =>
    ".L${labelX8664Instr.identifier}:";

  @override
  String visitSetCCX8664Instr(SetCCX8664Instr setCcx8664Instr) {
    final operand = setCcx8664Instr.operand is RegisterX8664Operand 
      ? RegisterX8664Operand((setCcx8664Instr.operand as RegisterX8664Operand).reg, .lowByte).accept(this)
      : setCcx8664Instr.operand.accept(this);

    return "set${setCcx8664Instr.condCode.name} $operand";
  }
}

class X8664AsmPrettifier implements X8664InstrVisitor<String>, X8664OperandVisitor<String> {
  static String prettify(X8664ProgramASM x8664programASM) => X8664AsmPrettifier().visitProgram(x8664programASM);
  
  String visitProgram(X8664ProgramASM x8664programASM) => "X8664ProgramAsm(${visitFunction(x8664programASM.function)})";
  
  String visitFunction(X8664FunctionASM function) => 
    "Function(${function.name}, ${function.instrs.map((instr) => instr.accept(this)).join(", ")})";

  @override
  String visitAllocateStackX8664Instr(AllocateStackX8664Instr alloc) => "AllocateStack(${alloc.amount})";
  
  @override
  String visitBinaryX8664Instr(BinaryX8664Instr binaryX8664Instr) => 
    "Binary(${binaryX8664Instr.operator.name}, ${binaryX8664Instr.lhs.accept(this)}, ${binaryX8664Instr.rhs.accept(this)})";
  
  @override
  String visitImmediateX8664Operand(ImmediateX8664Operand immediateX8664Operand) => 
    "Immediate(${immediateX8664Operand.value})";
  
  @override
  String visitMoveX8664Instr(MoveX8664Instr moveX8664Instr) => 
    "Move(${moveX8664Instr.src.accept(this)}, ${moveX8664Instr.dst.accept(this)})";
  
  @override
  String visitPseudoX8664Operand(PseudoX8664Operand pseudoX8664Operand) => "Pseudo(${pseudoX8664Operand.id})";
  
  @override
  String visitReturnX8664Instr(ReturnX8664Instr returnX8664Instr) => "Return()";
  
  @override
  String visitStackX8664Operand(StackX8664Operand stackX8664Operand) => 
    "Stack(${stackX8664Operand.value})";
  
  @override
  String visitUnaryX8664Instr(UnaryX8664Instr unaryX8664Instr) => 
    "Unary(${unaryX8664Instr.operator.name}, ${unaryX8664Instr.operand.accept(this)})";
  
  @override
  String visitRegisterX8664Operand(RegisterX8664Operand registerX8664Operand) => 
    "Register(${registerX8664Operand.reg}, ${registerX8664Operand.size})";
  
  @override
  String visitCdqX8664Instr(CdqX8664Instr cdqX8664Instr) => "Cdq()";
  
  @override
  String visitIdivX8664Instr(IdivX8664Instr idivX8664Instr) => 
    "Idiv(${idivX8664Instr.operand.accept(this)})";
  
  @override
  String visitCmpX8664Instr(CmpX8664Instr cmpX8664Instr) => 
    "Cmp(${cmpX8664Instr.lhs.accept(this)}, ${cmpX8664Instr.rhs.accept(this)})";
  
  @override
  String visitJmpCCX8664Instr(JmpCCX8664Instr jmpCcx8664Instr) => 
    "JmpCC(${jmpCcx8664Instr.condCode.name}, ${jmpCcx8664Instr.identifier})";
  
  @override
  String visitJmpX8664Instr(JmpX8664Instr jmpX8664Instr) => 
    "Jmp(${jmpX8664Instr.identifier})";
  
  @override
  String visitLabelX8664Instr(LabelX8664Instr labelX8664Instr) => 
    "Label(${labelX8664Instr.identifier})";
  
  @override
  String visitSetCCX8664Instr(SetCCX8664Instr setCcx8664Instr) => 
    "SetCC(${setCcx8664Instr.condCode.name}, ${setCcx8664Instr.operand.accept(this)})";
}

class X8664FunctionASM {
  final String name;
  final List<X8664Instr> instrs;

  X8664FunctionASM(this.name, this.instrs);
}

enum X8664RegisterSize {
  lowByte,
  highByte,
  short,
  word,
  quadWord,
}

enum X8664Register {
  xa({ 
    .lowByte: 'al',
    .highByte: 'ah',
    .short: 'ax',
    .word: 'eax',
    .quadWord: 'rax',
  }),
  xb({ 
    .lowByte: 'bl',
    .highByte: 'bh',
    .short: 'bx',
    .word: 'ebx',
    .quadWord: 'rbx',
  }),
  xc({ 
    .lowByte: 'cl',
    .highByte: 'ch',
    .short: 'cx',
    .word: 'ecx',
    .quadWord: 'rcx',
  }),
  xd({ 
    .lowByte: 'dl',
    .highByte: 'dh',
    .short: 'dx',
    .word: 'edx',
    .quadWord: 'rdx',
  }),
  r10({
    .lowByte: 'r10b',
    .short: 'r10w',
    .word: 'r10d',
    .quadWord: 'r10',  
  }),
  r11({
    .lowByte: 'r11b',
    .short: 'r11w',
    .word: 'r11d',
    .quadWord: 'r11',  
  }),
  r12({
    .lowByte: 'r12b',
    .short: 'r12w',
    .word: 'r12d',
    .quadWord: 'r12',
  });

  final Map<X8664RegisterSize, String> names;

  const X8664Register(this.names);
}

enum X8664BinaryOperator {
  add,
  sub,
  imul,
  xor,
  and,
  or,
  shl,
  sal,
  shr,
  sar,
}

enum X8664UnaryOperator {
  neg,
  not,
}

enum X8664CondCode {
  e,
  ne,
  g,
  ge,
  l,
  le,
}