name: tree_builder
description: build ast, tacky_ir, and asm tree
version: 1.0.0

environment:
  sdk: ^3.9.0-100.2.beta

dependencies:
  code_builder: ^4.10.1
  dart_style: ^3.1.0
  change_case: ^2.2.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
